# Version de compréhension du Docker compose
version: "3.9"
services:

  db:
    image: mariadb
    container_name: db_projet14
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    networks:
      - projet14

  phpmyadmin:
    image: adminer
    container_name: adminer_projet14
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - projet14

  www:
    build: php
    container_name: www_projet14
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - projet14

networks:
  projet14:

volumes:
  db-data: